openapi: 3.0.0
info:
  title: N8N M-Files
  version: 1.0.0
  description: API naar de Siers M-Files omgeving
servers:
  - url: '{{base_url}}'
paths:
  /mfiles/subproject:
    post:
      summary: create subproject HOP
      responses:
        '201':
          description: '201'
      tags:
        - Subproject
      description: Het format van de oude JSON, deze is compatible met deze API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ClientID:
                  type: string
                Method:
                  type: string
                Nummer:
                  type: string
                Omschrijving:
                  type: string
                Hoofdproject:
                  type: string
                Status:
                  type: string
                Regio:
                  type: string
                Uitvoeringstype:
                  type: string
                Bedrijfsleider:
                  type: string
                Teamleider:
                  type: string
                Werkvoorbereider:
                  type: string
                Uitvoerder:
                  type: string
                Plaats:
                  type: string
                Gemeente:
                  type: string
                Projectreferentie:
                  type: string
                Kenmerk:
                  type: string
            example:
              ClientID: oude call
              Method: wordt genegeerd
              Nummer: Z00000
              Omschrijving: het nieuwe subproject nummer 4
              Hoofdproject: AA00001
              Status: wordt genegeerd
              Regio: 6BCE4B38-4A23-4ED5-9C47-0A21AB9A06E9
              Uitvoeringstype: wordt genegeerd
              Bedrijfsleider: Henk Bente
              Teamleider: Frank Wolsink
              Werkvoorbereider: Frank Wolsink
              Uitvoerder: Frank Wolsink
              Plaats: Oldenzaal
              Gemeente: wordt genegeerd
              Projectreferentie: wordt genegeerd
              Kenmerk: wordt genegeerd
    put:
      summary: update subproject HOP
      responses:
        '202':
          description: '200'
          content:
            application/json:
              schema:
                type: object
                properties:
                  nummer:
                    type: string
                  naam:
                    type: string
                  hoofdproject:
                    type: string
              example:
                nummer: Gewijzigde nummer
                naam: Gewijzigde naam
                hoofdproject: Z00103
      tags:
        - Subproject
      description: Een subproject wordt ge-update.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ClientID:
                  type: string
                Method:
                  type: string
                ObjectGUID:
                  type: string
                Nummer:
                  type: string
                Omschrijving:
                  type: string
                Hoofdproject:
                  type: string
                Status:
                  type: string
                Regio:
                  type: string
                Uitvoeringstype:
                  type: string
                Bedrijfsleider:
                  type: string
                Teamleider:
                  type: string
                Werkvoorbereider:
                  type: string
                Uitvoerder:
                  type: string
                Plaats:
                  type: string
                Gemeente:
                  type: string
                Projectreferentie:
                  type: string
                Kenmerk:
                  type: string
            example:
              ClientID: oude call
              Method: wordt genegeerd
              ObjectGUID: '{99925761-CCDE-4BA6-8BF6-5163F869FBC1}'
              Nummer: Gewijzigde nummer
              Omschrijving: Gewijzigde naam
              Hoofdproject: wordt genegeerd
              Status: '{7184AE09-DAA8-4C2A-976E-5155D5E50921}'
              Regio: wordt genegeerd
              Uitvoeringstype: wordt genegeerd
              Bedrijfsleider: Jeroen Kloppers
              Teamleider: Frank Wolsink
              Werkvoorbereider: Harm Thuis
              Uitvoerder: Frank Wolsink
              Plaats: Gewijzigde plaats
              Gemeente: wordt genegeerd
              Projectreferentie: wordt genegeerd
              Kenmerk: wordt genegeerd
    get:
      summary: get subproject
      parameters:
        - name: nummer
          in: query
          description: subprojectnummer
          schema:
            type: string
          example: AA00121
      responses:
        '200':
          description: '200'
      tags:
        - Subproject
      description: een subproject wordt uitgelezen
  /mfiles/dossier:
    post:
      summary: create dossier HOP
      responses:
        '501':
          description: '501'
      tags:
        - Dossier
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ClientID:
                  type: string
                Method:
                  type: string
                Code:
                  type: string
                Omschrijving:
                  type: string
                Project:
                  type: string
                Engineer:
                  type: string
                Discipline:
                  type: string
                SoortWerk:
                  type: string
                Opdrachtgever:
                  type: string
                OGVerantwoordelijke:
                  type: string
                OGInkoopcode:
                  type: string
                Prijsboek:
                  type: string
            example:
              ClientID: oude call
              Method: wordt genegeerd
              Code: dossiernummer
              Omschrijving: Gas - Gestuurde boring
              Project: '{E0E56B22-7656-4F4C-9575-094477A79D75}'
              Engineer: wordt genegeerd
              Discipline: Gas
              SoortWerk: wordt genegeerd
              Opdrachtgever: 100120 - Gemeente Amsterdam
              OGVerantwoordelijke: A. Peters - Contactpersoon
              OGInkoopcode: PO-778899 Externe Referentie
              Prijsboek: wordt genegeerd
    get:
      summary: get dossier
      parameters:
        - name: nummer
          in: query
          description: nummer van het dossier
          schema:
            type: string
          example: IO008500
      responses:
        '200':
          description: '200'
      tags:
        - Dossier
  /mfiles/url_subproject:
    post:
      summary: project url HOP
      responses: {}
      tags:
        - URL
      description: project URL ophalen met oude JSON
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ClientID:
                  type: string
                Method:
                  type: string
                ObjectGUID:
                  type: string
            example:
              ClientID: oude call
              Method: wordt genegeerd
              ObjectGUID: '{E0E56B22-7656-4F4C-9575-094477A79D75}'
    get:
      summary: project url
      parameters:
        - name: subprojectGUID
          in: query
          description: GUID van het subproject
          schema:
            type: string
          example: '{E0E56B22-7656-4F4C-9575-094477A79D75}'
      responses: {}
      tags:
        - URL
      description: project URL ophalen
  /mfiles/url_dossier:
    post:
      summary: dossier url HOP
      responses: {}
      tags:
        - URL
      description: dossier URL ophalen met oude JSON
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ClientID:
                  type: string
                Method:
                  type: string
                ObjectGUID:
                  type: string
            example:
              ClientID: oude call
              Method: wordt genegeerd
              ObjectGUID: '{87878676-B41E-4C1E-87A5-BD3218E242CF}'
    get:
      summary: dossier url
      parameters:
        - name: dossierGUID
          in: query
          description: GUID van het Dossier
          schema:
            type: string
          example: '{87878676-B41E-4C1E-87A5-BD3218E242CF}'
      responses: {}
      tags:
        - URL
      description: dossier URL ophalen
  /mfiles/hoofdproject:
    get:
      summary: get hoofdproject
      parameters:
        - name: nummer
          in: query
          description: nummer van het hoofdproject
          schema:
            type: string
          example: Z00000
      responses: {}
      tags:
        - Hoofdproject
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
